#!/bin/sh
#
# UKI post-remove hook for dracut.
#
# Arguments passed to this script: $1 pkgname, $2 version.
#
PKGNAME="$1"
VERSION="$2"

# Load variables from dracut-uki-hook
. "${ROOTDIR}/etc/default/dracut-uki-hook"
if [ "x${UKI_ON}" != x1 ]; then
  exit 0
fi

# get major version, e.g. "4.8" for "linux4.8"
major_version=$(echo $PKGNAME | cut -c 6-)

rm -f ${EFI_MOUNT}/${UKI_FILE_DIR}/${BASE_UKI_FILE}-${VERSION}*.efi
